# Generated by Django 5.1.7 on 2025-12-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_course_id_alter_lesson_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='картинки/', verbose_name='Превью курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_in_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Уроки курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(blank=True, null=True, upload_to='картинки/', verbose_name='Превью урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
